<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <SupportedOSPlatformVersion>10.0.22621.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaXaml Remove="Views\Promozione\Fidelity\FidelityGroupView.axaml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Views\Promozione\Fidelity\FidelityGroupView.axaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\ControlStyles\ControlStyles.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
    <ProjectReference Include="..\SysNet\SysNet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\Listino\DTO\" />
    <Folder Include="ViewModels\Nuova cartella\" />
    <Folder Include="Views\Promozione\Fidelity\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Listino\ListinoView.axaml.cs">
      <DependentUpon>ListinoView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
