<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaXaml Remove="ViewModels\Tessera\**" />
    <AvaloniaXaml Remove="Views\Tessera\**" />
    <Compile Remove="ViewModels\Tessera\**" />
    <Compile Remove="Views\Tessera\**" />
    <EmbeddedResource Remove="ViewModels\Tessera\**" />
    <EmbeddedResource Remove="Views\Tessera\**" />
    <None Remove="ViewModels\Tessera\**" />
    <None Remove="Views\Tessera\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\ControlStyles\ControlStyles.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
    <ProjectReference Include="..\SysNet\SysNet.csproj" />
  </ItemGroup>

</Project>
